GET http://localhost:3000/task
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhdmlAZGF2aS5jb20iLCJpZCI6IjY1NjdkZGUwMDg3MzlhNzA1NGQ4NTdlZSIsImlhdCI6MTcwMTMwNjM2OH0.PHOG4f-dAaGT5v4Sx6yMgrfFcAcBuoVpdWI_5RaYK10

